# Generated by Django 5.2.5 on 2025-09-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='category',
            field=models.CharField(choices=[('charger', 'Charger'), ('bag', 'Bag'), ('mouse', 'Mouse'), ('keyboard', 'Keyboard'), ('adapter', 'Adapter'), ('stand', 'Stand'), ('laptop', 'Laptop'), ('printer', 'Printer'), ('memory', 'Memory'), ('spiker', 'Spiker'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
